name: "Copilot Setup Steps"

# Automatically run the setup steps when they are changed to allow for easy validation, and
# allow manual testing through the repository's "Actions" tab
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    runs-on: macos-latest

    # Set the permissions to the lowest permissions possible needed for your steps.
    # Copilot will be given its own token for its operations.
    permissions:
      # If you want to clone the repository as part of your setup steps, for example to install dependencies, you'll need the `contents: read` permission. If you don't clone the repository in your setup steps, Copilot will do this for you automatically after the steps complete.
      contents: read

    # Set environment variables from secrets
    env:
      TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}

    # You can define any steps you want, and they will run before the agent starts.
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          # Install Homebrew if not present
          if ! command -v brew > /dev/null 2>&1; then
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            eval "$(/opt/homebrew/bin/brew shellenv)"
          fi
          
          # Install required packages
          brew install \
            make \
            qemu \
            parted \
            dosfstools \
            e2fsprogs \
            xz \
            unzip \
            wget \
            curl \
            git \
            shellcheck \
            cpio \
            gzip \
            rsync \
            util-linux \
            jq

      - name: Install Docker (for testing containers)
        run: |
          # Docker Desktop is usually pre-installed on macOS GitHub runners
          # If not available, install Docker Desktop
          if ! command -v docker > /dev/null 2>&1; then
            echo "Docker not found - installing Docker Desktop"
            brew install --cask docker
            # Start Docker Desktop
            open -a Docker
            # Wait for Docker to start
            while ! docker info > /dev/null 2>&1; do
              echo "Waiting for Docker to start..."
              sleep 5
            done
          fi

      - name: Verify installation
        run: |
          make --version
          qemu-system-aarch64 --version
          docker --version
          shellcheck --version
          xz --version
          # parted --version  # May not be available on macOS
          # diskutil info / | head -5  # macOS disk utility instead

      - name: Create required directories
        run: |
          mkdir -p images4rpi
          mkdir -p pi5_installer_work
          mkdir -p qemu_test

      - name: Set up shell environment
        run: |
          echo "export PATH=/opt/homebrew/bin:\$PATH" >> ~/.zshrc
          echo "alias ll='ls -la'" >> ~/.zshrc
