name: "Copilot Setup Steps"

# Automatically run the setup steps when they are changed to allow for easy validation, and
# allow manual testing through the repository's "Actions" tab
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    runs-on: macos-latest-xlarge

    # Set the permissions to the lowest permissions possible needed for your steps.
    # Copilot will be given its own token for its operations.
    permissions:
      # If you want to clone the repository as part of your setup steps, for example to install dependencies, you'll need the `contents: read` permission. If you don't clone the repository in your setup steps, Copilot will do this for you automatically after the steps complete.
      contents: read

    # Set environment variables from secrets
    env:
      TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}

    # You can define any steps you want, and they will run before the agent starts.
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            make \
            qemu-system-arm \
            qemu-user-static \
            binfmt-support \
            parted \
            dosfstools \
            e2fsprogs \
            xz-utils \
            unzip \
            wget \
            curl \
            git \
            shellcheck \
            cpio \
            gzip \
            rsync \
            fdisk \
            util-linux \
            kpartx

      - name: Install Docker (for testing containers)
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          sudo usermod -aG docker $USER
          # Clean up installation script
          rm -f get-docker.sh

      - name: Verify installation
        run: |
          make --version
          qemu-system-arm --version
          sudo docker --version
          shellcheck --version
          xz --version
          parted --version
          losetup --version
          kpartx -h || true

      - name: Create required directories
        run: |
          mkdir -p images4rpi
          mkdir -p pi5_installer_work
          mkdir -p qemu_test

      - name: Set up shell environment
        run: |
          echo "export PATH=/usr/local/bin:\$PATH" >> ~/.bashrc
          echo "alias ll='ls -la'" >> ~/.bashrc
